"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const detritus_client_1 = require("detritus-client");
const detritus_utils_1 = require("detritus-utils");
const { ChannelTypes, DetritusKeys, DiscordKeys, GuildExplicitContentFilterTypes, Locales: DiscordLocales, Permissions, PresenceStatuses: Statuses, VerificationLevels, } = detritus_client_1.Constants;
exports.DiscordLocales = DiscordLocales;
exports.BooleanEmojis = Object.freeze({
    NO: '❌',
    YES: '✅',
});
exports.ChannelTypesText = Object.freeze({
    [ChannelTypes.GUILD_TEXT]: 'Guild Text',
    [ChannelTypes.DM]: 'Direct Message',
    [ChannelTypes.GUILD_VOICE]: 'Guild Voice',
    [ChannelTypes.GROUP_DM]: 'Direct Message Group',
    [ChannelTypes.GUILD_CATEGORY]: 'Guild Category',
    [ChannelTypes.GUILD_NEWS]: 'Guild News',
    [ChannelTypes.GUILD_STORE]: 'Guild Store',
    [ChannelTypes.GUILD_LFG_LISTINGS]: 'Guild LFG Listings',
});
exports.CommandTypes = detritus_utils_1.Tools.normalize({
    IMAGE: null,
    INFO: null,
    OWNER: null,
    SEARCH: null,
    SETTINGS: null,
    TOOLS: null,
    UTILS: null,
});
exports.DateOptions = Object.freeze({
    timeZone: 'America/New_York',
});
exports.EmbedBrands = Object.freeze({
    DUCK_DUCK_GO: 'https://cdn.notsobot.com/brands/duck-duck-go.png',
    GOOGLE_GO: 'https://cdn.notsobot.com/brands/google-go.png',
    NOTSOBOT: 'https://cdn.notsobot.com/brands/notsobot.png?cache-bust-this-di',
    URBAN: 'https://cdn.notsobot.com/brands/urban-dictionary.png?cache-bust-this-di',
    WOLFRAM_ALPHA: 'https://cdn.notsobot.com/brands/wolfram-alpha.png',
    YOUTUBE: 'https://cdn.notsobot.com/brands/youtube.png',
});
exports.EmbedColors = Object.freeze({
    DEFAULT: 8684933,
    ERROR: 15746887,
});
exports.GoogleCardTypes = detritus_utils_1.Tools.normalize({
    CALCULATOR: null,
    COMPLEMENTARY_RESULTS: null,
    CURRENCY: null,
    DEFINITION: null,
    KNOWLEDGE_RESULT: null,
    PEOPLE_ALSO_ASK: null,
    TIME: null,
    TRANSLATION: null,
    UNITS: null,
    UNKNOWN: null,
    WEATHER: null,
});
exports.GOOGLE_CARD_TYPES_SUPPORTED = Object.freeze([
    exports.GoogleCardTypes.CALCULATOR,
    exports.GoogleCardTypes.CURRENCY,
    exports.GoogleCardTypes.TIME,
    exports.GoogleCardTypes.UNITS,
    exports.GoogleCardTypes.WEATHER,
]);
exports.GoogleLocales = Object.freeze({
    AMHARIC: 'am',
    ARABIC: 'ar',
    BASQUE: 'eu',
    BENGALI: 'bn',
    BULGARIAN: 'bg',
    CATALAN: 'ca',
    CHEROKEE: 'chr',
    CHINESE_SIMPLIFIED: 'zh-CN',
    CHINESE_TRADITIONAL: 'zh-TW',
    CROATIAN: 'hr',
    CZECH: 'cs',
    DANISH: 'da',
    DUTCH: 'nl',
    ENGLISH: 'en',
    ENGLISH_UK: 'en-GB',
    ESTONIAN: 'et',
    FILIPINO: 'fil',
    FINNISH: 'fi',
    FRENCH: 'fr',
    GERMAN: 'de',
    GREEK: 'el',
    GUJARATI: 'gu',
    HEBREW: 'iw',
    HINDI: 'hi',
    HUNGARIAIN: 'hu',
    ICELANDIC: 'is',
    INDONESIAN: 'id',
    ITALIAN: 'it',
    JAPANESE: 'ja',
    KANNADA: 'kn',
    KOREAN: 'ko',
    LATVIAN: 'lv',
    LITHUANIAN: 'lt',
    MALAY: 'ms',
    MALAYALAM: 'ml',
    MARATHI: 'mr',
    NORWEGIAN: 'no',
    POLISH: 'pl',
    PORTUGUESE_BRAZIL: 'pt-BR',
    PORTUGUESE_PORTUGAL: 'pt-PT',
    ROMANIAN: 'ro',
    RUSSIAN: 'ru',
    SERBIAN: 'sr',
    SLOVAK: 'sk',
    SLOVENIAN: 'sl',
    SPANISH: 'es',
    SWAHILI: 'sw',
    SWEDISH: 'sv',
    TAMIL: 'ta',
    TELUGU: 'te',
    THAI: 'th',
    TURKISH: 'tr',
    URDU: 'ur',
    UKRAINIAN: 'uk',
    VIETNAMESE: 'vi',
    WELSH: 'cy',
});
exports.GOOGLE_LOCALES = Object.freeze(Object.values(exports.GoogleLocales));
exports.GoogleLocalesText = Object.freeze({
    [exports.GoogleLocales.AMHARIC]: 'Amharic',
    [exports.GoogleLocales.ARABIC]: 'Arabic',
    [exports.GoogleLocales.BASQUE]: 'Basque',
    [exports.GoogleLocales.BENGALI]: 'Bengali',
    [exports.GoogleLocales.BULGARIAN]: 'Bulgarian',
    [exports.GoogleLocales.CATALAN]: 'Catalan',
    [exports.GoogleLocales.CHEROKEE]: 'Cherokee',
    [exports.GoogleLocales.CHINESE_SIMPLIFIED]: 'Chinese (Simplified)',
    [exports.GoogleLocales.CHINESE_TRADITIONAL]: 'Chinese (Traditional)',
    [exports.GoogleLocales.CROATIAN]: 'Croatian',
    [exports.GoogleLocales.CZECH]: 'Czech',
    [exports.GoogleLocales.DANISH]: 'Danish',
    [exports.GoogleLocales.DUTCH]: 'Dutch',
    [exports.GoogleLocales.ENGLISH]: 'English (US)',
    [exports.GoogleLocales.ENGLISH_UK]: 'English (UK)',
    [exports.GoogleLocales.ESTONIAN]: 'Estonian',
    [exports.GoogleLocales.FILIPINO]: 'Filipino',
    [exports.GoogleLocales.FINNISH]: 'Finnish',
    [exports.GoogleLocales.FRENCH]: 'French',
    [exports.GoogleLocales.GERMAN]: 'German',
    [exports.GoogleLocales.GREEK]: 'Greek',
    [exports.GoogleLocales.GUJARATI]: 'Gujarati',
    [exports.GoogleLocales.HEBREW]: 'Hebrew',
    [exports.GoogleLocales.HINDI]: 'Hindi',
    [exports.GoogleLocales.HUNGARIAIN]: 'Hungarian',
    [exports.GoogleLocales.ICELANDIC]: 'Icelandic',
    [exports.GoogleLocales.INDONESIAN]: 'Indonesian',
    [exports.GoogleLocales.ITALIAN]: 'Italian',
    [exports.GoogleLocales.JAPANESE]: 'Japanese',
    [exports.GoogleLocales.KANNADA]: 'Kannada',
    [exports.GoogleLocales.KOREAN]: 'Korean',
    [exports.GoogleLocales.LATVIAN]: 'Latvian',
    [exports.GoogleLocales.LITHUANIAN]: 'Lithuanian',
    [exports.GoogleLocales.MALAYALAM]: 'Malayalam',
    [exports.GoogleLocales.MALAY]: 'Malay',
    [exports.GoogleLocales.MARATHI]: 'Marathi',
    [exports.GoogleLocales.NORWEGIAN]: 'Norwegian',
    [exports.GoogleLocales.POLISH]: 'Polish',
    [exports.GoogleLocales.PORTUGUESE_BRAZIL]: 'Portuguese (Brazil)',
    [exports.GoogleLocales.PORTUGUESE_PORTUGAL]: 'Portuguese (Portugal)',
    [exports.GoogleLocales.ROMANIAN]: 'Romanian',
    [exports.GoogleLocales.RUSSIAN]: 'Russian',
    [exports.GoogleLocales.SERBIAN]: 'Serbian',
    [exports.GoogleLocales.SLOVAK]: 'Slovak',
    [exports.GoogleLocales.SLOVENIAN]: 'Slovenian',
    [exports.GoogleLocales.SPANISH]: 'Spanish',
    [exports.GoogleLocales.SWAHILI]: 'Swahili',
    [exports.GoogleLocales.SWEDISH]: 'Swedish',
    [exports.GoogleLocales.TAMIL]: 'Tamil',
    [exports.GoogleLocales.TELUGU]: 'Telugu',
    [exports.GoogleLocales.THAI]: 'Thai',
    [exports.GoogleLocales.TURKISH]: 'Turkish',
    [exports.GoogleLocales.URDU]: 'Urdu',
    [exports.GoogleLocales.VIETNAMESE]: 'Vietnamese',
    [exports.GoogleLocales.WELSH]: 'Welsh',
});
exports.GoogleLocaleFromDiscord = Object.freeze({
    [DiscordLocales.ENGLISH_US]: exports.GoogleLocales.ENGLISH,
    [DiscordLocales.SPANISH]: exports.GoogleLocales.SPANISH,
    [DiscordLocales.SWEDISH]: exports.GoogleLocales.SWEDISH,
});
exports.GuildExplicitContentFilterTypeTexts = Object.freeze({
    [GuildExplicitContentFilterTypes.DISABLED]: 'Disabled',
    [GuildExplicitContentFilterTypes.MEMBERS_WITHOUT_ROLES]: 'No Roles',
    [GuildExplicitContentFilterTypes.ALL_MEMBERS]: 'Everyone',
});
exports.PermissionsKeys = Object.freeze(detritus_utils_1.Tools.normalize(Object.assign({}, Permissions)));
exports.PermissionsText = Object.freeze({
    [exports.PermissionsKeys.ADD_REACTIONS]: 'Add Reactions',
    [exports.PermissionsKeys.ADMINISTRATOR]: 'Administrator',
    [exports.PermissionsKeys.ATTACH_FILES]: 'Attach Files',
    [exports.PermissionsKeys.BAN_MEMBERS]: 'Ban Members',
    [exports.PermissionsKeys.CHANGE_NICKNAME]: 'Change Nickname',
    [exports.PermissionsKeys.CHANGE_NICKNAMES]: 'Change Nicknames',
    [exports.PermissionsKeys.CONNECT]: 'Connect',
    [exports.PermissionsKeys.CREATE_INSTANT_INVITE]: 'Create Instant Invite',
    [exports.PermissionsKeys.DEAFEN_MEMBERS]: 'Deafen Members',
    [exports.PermissionsKeys.EMBED_LINKS]: 'Embed Links',
    [exports.PermissionsKeys.KICK_MEMBERS]: 'Kick Members',
    [exports.PermissionsKeys.MANAGE_CHANNELS]: 'Manage Channels',
    [exports.PermissionsKeys.MANAGE_EMOJIS]: 'Manage Emojis',
    [exports.PermissionsKeys.MANAGE_GUILD]: 'Manage Guild',
    [exports.PermissionsKeys.MANAGE_MESSAGES]: 'Manage Messages',
    [exports.PermissionsKeys.MANAGE_ROLES]: 'Manage Roles',
    [exports.PermissionsKeys.MANAGE_WEBHOOKS]: 'Manage Webhooks',
    [exports.PermissionsKeys.MENTION_EVERYONE]: 'Mention Everyone',
    [exports.PermissionsKeys.MOVE_MEMBERS]: 'Move Members',
    [exports.PermissionsKeys.MUTE_MEMBERS]: 'Mute Members',
    [exports.PermissionsKeys.PRIORITY_SPEAKER]: 'Priority Speaker',
    [exports.PermissionsKeys.READ_MESSAGE_HISTORY]: 'Read Message History',
    [exports.PermissionsKeys.SEND_MESSAGES]: 'Send Messages',
    [exports.PermissionsKeys.SEND_TTS_MESSAGES]: 'Text-To-Speech',
    [exports.PermissionsKeys.SPEAK]: 'Speak',
    [exports.PermissionsKeys.STREAM]: 'Go Live',
    [exports.PermissionsKeys.USE_EXTERNAL_EMOJIS]: 'Use External Emojis',
    [exports.PermissionsKeys.USE_VAD]: 'Voice Auto Detect',
    [exports.PermissionsKeys.VIEW_AUDIT_LOG]: 'View Audit Logs',
    [exports.PermissionsKeys.VIEW_CHANNEL]: 'View Channel',
});
exports.PresenceStatusColors = Object.freeze({
    [Statuses.ONLINE]: 4437377,
    [Statuses.DND]: 15746887,
    [Statuses.IDLE]: 16426522,
    [Statuses.OFFLINE]: 7634829,
});
exports.PresenceStatusTexts = Object.freeze({
    [Statuses.ONLINE]: 'Online',
    [Statuses.DND]: 'Do Not Disturb',
    [Statuses.IDLE]: 'Idle',
    [Statuses.OFFLINE]: 'Offline',
});
exports.VerificationLevelTexts = Object.freeze({
    [VerificationLevels.NONE]: 'None',
    [VerificationLevels.LOW]: 'Low',
    [VerificationLevels.MEDIUM]: 'Medium',
    [VerificationLevels.HIGH]: 'High',
    [VerificationLevels.VERY_HIGH]: 'Very High',
});
exports.YoutubeResultTypes = Object.freeze({
    CHANNEL: 0,
    VIDEO: 1,
});
exports.PERMISSIONS_KEYS_ADMIN = Object.freeze([
    exports.PermissionsKeys.ADMINISTRATOR,
    exports.PermissionsKeys.BAN_MEMBERS,
    exports.PermissionsKeys.CHANGE_NICKNAMES,
    exports.PermissionsKeys.KICK_MEMBERS,
    exports.PermissionsKeys.MANAGE_CHANNELS,
    exports.PermissionsKeys.MANAGE_EMOJIS,
    exports.PermissionsKeys.MANAGE_GUILD,
    exports.PermissionsKeys.MANAGE_MESSAGES,
    exports.PermissionsKeys.MANAGE_ROLES,
    exports.PermissionsKeys.MANAGE_WEBHOOKS,
    exports.PermissionsKeys.VIEW_AUDIT_LOG,
]);
exports.PERMISSIONS_KEYS_TEXT = Object.freeze([
    exports.PermissionsKeys.ADD_REACTIONS,
    exports.PermissionsKeys.ATTACH_FILES,
    exports.PermissionsKeys.CREATE_INSTANT_INVITE,
    exports.PermissionsKeys.EMBED_LINKS,
    exports.PermissionsKeys.MENTION_EVERYONE,
    exports.PermissionsKeys.READ_MESSAGE_HISTORY,
    exports.PermissionsKeys.SEND_MESSAGES,
    exports.PermissionsKeys.SEND_TTS_MESSAGES,
    exports.PermissionsKeys.USE_EXTERNAL_EMOJIS,
    exports.PermissionsKeys.VIEW_CHANNEL,
]);
exports.PERMISSIONS_KEYS_VOICE = Object.freeze([
    exports.PermissionsKeys.CONNECT,
    exports.PermissionsKeys.CREATE_INSTANT_INVITE,
    exports.PermissionsKeys.DEAFEN_MEMBERS,
    exports.PermissionsKeys.MOVE_MEMBERS,
    exports.PermissionsKeys.MUTE_MEMBERS,
    exports.PermissionsKeys.PRIORITY_SPEAKER,
    exports.PermissionsKeys.SPEAK,
    exports.PermissionsKeys.STREAM,
    exports.PermissionsKeys.USE_VAD,
    exports.PermissionsKeys.VIEW_CHANNEL,
]);
exports.PRESENCE_CLIENT_STATUS_KEYS = Object.freeze([
    DetritusKeys[DiscordKeys.DESKTOP],
    DetritusKeys[DiscordKeys.MOBILE],
    DetritusKeys[DiscordKeys.WEB],
]);
